<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<UseWPF>True</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>FrostyEditor</RootNamespace>
    <AssemblyName>FrostyEditor</AssemblyName>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SignAssembly>false</SignAssembly>
	<AssemblyOriginatorKeyFile>FrostyEditor.pfx</AssemblyOriginatorKeyFile>
	<Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
	<Platforms>x64</Platforms>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
	
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Final|x64' ">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Developer - Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG;FROSTY_DEVELOPER</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Alpha|x64'">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE;FROSTY_ALPHA</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
	
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Beta|x64' ">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE;FROSTY_BETA</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\FrostyHash\FrostyHash.csproj" />
    <ProjectReference Include="..\FrostyModSupport\FrostyModSupport.csproj" />
    <ProjectReference Include="..\FrostyPlugin\FrostyCore.csproj" />
    <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
    <ProjectReference Include="..\FrostyControls\FrostyControls.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
	
  <ItemGroup>
    <Resource Include="AppIcon.ico" />
	<Resource Include="Images\**\*" />
	<Resource Include="Shaders\ShaderTemplate.txt" />
    <Resource Include="ChangeLog.txt" />
    <Resource Include="Credits.txt" />

	<Content Include="Resources\FifaKitPreviewStance.dat" CopyToOutputDirectory="PreserveNewest" />
	<Content Include="Resources\Meshes\**\*" CopyToOutputDirectory="PreserveNewest" />
	<Content Include="Resources\Textures\**\*" CopyToOutputDirectory="PreserveNewest" />
	<Content Include="Shaders\*.bin" CopyToOutputDirectory="PreserveNewest" />
	<Content Include="Shaders\*.xml" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Shaders\shaders.txt" CopyToOutputDirectory="PreserveNewest" />
	<Content Include="ThirdParty\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="ThirdParty\FrostyMovie.dll" Condition=" '$(Configuration)' == 'Developer - Debug' " />
  </ItemGroup>
	
</Project>